### ISSUE TITLE
Error in google search

### ISSUE THREAD

**Issue by dftaher** [jimmycuadra/lita-google#5]
I receive the following error when trying to use google search,

```
[2016-05-05 04:58:49 UTC] DEBUG: Dispatching message to Lita::Handlers::Google#search.
[2016-05-05 04:58:50 UTC] ERROR: Lita::Handlers::Google crashed. The exception was:
undefined method '[]' for nil:NilClass
Full backtrace:
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-google-1.1.0/lib/lita/handlers/google.rb:43:in 'search'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in 'public_send'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in 'call'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:97:in 'dispatch_to_route'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:82:in 'block in dispatch'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in 'map'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in 'dispatch'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/robot.rb:69:in 'block in receive'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/2.2.0/set.rb:283:in 'each_key'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/2.2.0/set.rb:283:in 'each'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in 'map'
/Users/dftaher/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in 'receive'
```

**Comment by zenvdeluca** [comment]
same as here

**Comment by oneillsj** [comment]
same

**Comment by jimmycuadra** [comment]
This is why this is happening:

``` ruby
# HTTP response from Google
{
  "responseData" => nil,
  "responseDetails" => "The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)",
  "responseStatus" => 403
}
```

Looks like this handler is gonna need an overhaul like lita-google-images had.

**Comment by bladedshard** [comment]
If anyone is still having issues with lita.   Post here or email me at flamer962@gmail.com and I'll share my config with you. 

As I was undergoing alot of issues.  Which I have now sorted out and if anyone is still having issues.  Let me know and ill share my config with you.
