### ISSUE TITLE
lita-google doesnt work at all

### ISSUE THREAD

**Issue by bladedshard** [jimmycuadra/lita-google#6]
Hello,

So I have lita-google installed and ready to go, as well as the config for it in the config file for lita.

In chat I type, lita, google <something>    and in my console I'm running lita.

I get this

```
ERROR: Lita::Handlers::Google crashed. The exception was:
undefined method `[]' for nil:NilClass
Full backtrace:
/var/lib/gems/2.1.0/gems/lita-google-1.1.0/lib/lita/handlers/google.rb:62:in `check_for_excluded_domains'
/var/lib/gems/2.1.0/gems/lita-google-1.1.0/lib/lita/handlers/google.rb:41:in `search'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/callback.rb:31:in `public_send'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/callback.rb:31:in `call'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:97:in `dispatch_to_route'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `map'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `dispatch'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/robot.rb:69:in `block in receive'
/usr/lib/ruby/2.1.0/set.rb:263:in `each_key'
/usr/lib/ruby/2.1.0/set.rb:263:in `each'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/robot.rb:66:in `map'
/var/lib/gems/2.1.0/gems/lita-4.7.1/lib/lita/robot.rb:66:in `receive'
/var/lib/gems/2.1.0/gems/lita-irc-2.0.3/lib/lita/adapters/irc/cinch_plugin.rb:38:in `dispatch'
/var/lib/gems/2.1.0/gems/lita-irc-2.0.3/lib/lita/adapters/irc/cinch_plugin.rb:18:in `execute'
/var/lib/gems/2.1.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:418:in `call'
/var/lib/gems/2.1.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:418:in `block (2 levels) in __register_matchers'
/var/lib/gems/2.1.0/gems/cinch-2.3.3/lib/cinch/handler.rb:99:in `call'
/var/lib/gems/2.1.0/gems/cinch-2.3.3/lib/cinch/handler.rb:99:in `block in call'

```

This is the part of my config I have for the google plugin.

```
  config.handlers.google.safe_search = :off
  config.handlers.google.excluded_domains = ["gawker.com", "funnyjunk.com", "dailymail.co.uk"]

```

Was wondering if someone could help me figure out why it wont work?

**Comment by jimmycuadra** [comment]
Probably the same issue as #5.
